musu_webukas/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index']);
Route::resource('categories', 'CategoryController')->only(['show']);
Route::resource('cart', 'CartController')->only(['index', 'store', 'destroy']);
Route::post('/checkout', 'CartController@checkout')->name('cart.checkout');
Route::resource('contacts', 'ContactController')->only(['index', 'store']);

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('orders', 'OrderController')->only(['index', 'show', 'destroy']);
    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoryController');
    Route::resource('contacts', 'ContactController')->only(['index', 'destroy']);
});

musu_webukas/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use App\Item;
use App\Product;
use App\Http\Requests\AddToCart;
use App\Http\Requests\Checkout;
use Illuminate\Http\Request;

class CartController extends Controller
{
    /**
     * Perform a checkout on the current cart
     *
     * @param  \App\Http\Requests\Checkout  $request
     * @return \Illuminate\Http\Response
     */
    public function checkout(Checkout $request)
    {
        $cart = session('cart', []);
        $order = Order::create($request->validated());
        foreach ($cart as $product_id => $quantity) {
            $order->products()->attach($product_id, ['quantity' => $quantity]);
        }
        $request->session()->forget('cart');
        return view('cart.checkout', ['order' => $order]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cart = collect(session('cart', []));
        $items = $cart->map(function($quantity, $product_id) {
            $product = Product::find($product_id);
            return ['product' => $product, 'quantity' => $quantity, 'price' => $product->price * $quantity];
        });
        $price = $items->sum('price');
        return view('cart.index', ['items' => $items, 'price' => $price]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\AddToCart  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddToCart $request)
    {
        $items = session('cart', []);
        $quantity = $request->input('quantity') ?? 1;
        $product_id = $request->input('product_id');
        if (array_key_exists($product_id, $items)) {
            $items[$product_id] += $quantity;
        } else {
            $items[$product_id] = $quantity;
        }
        session(['cart' => $items]);
        return redirect()->route('cart.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $product_id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $product_id)
    {
        $items = collect(session('cart', []));
        unset($items[$product_id]);
        session(['cart' => $items]);
        return redirect()->route('cart.index');
    }
}

musu_webukas/resources/views/cart/checkout.blade.php
@extends('layouts.app')

@section('title', "Užsakymas $order->id sėkmingai pateiktas")

@section('content')
<div class="container">
  <a role="button" class="btn btn-primary btn-lg btn-block" href="{{ route('products.index') }}">Grįžti į produktų
    sąrašą</a>
</div>
@endsection

musu_webukas/resources/views/cart/index.blade.php
@extends('layouts.app')

@section('title', 'Krepšelis')

@section('content')
<div class="container">

  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Paslauga</th>
            <th scope="col">Kaina</th>
            <th scope="col">Kiekis</th>
            <th scope="col">Suma &euro;</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @foreach ($items as $item)
          <tr>
            <th scope="row">{{ $item['product']->title }}</th>
            <td>{{ $item['product']->price}}</td>
            <td>{{ $item['quantity'] }}</td>
            <td>{{ $item['price'] }}</td>
            <td>
              <form action="{{ route('cart.destroy', ['product_id' => $item['product']->id]) }}" method="POST">
                @csrf
                @method("DELETE")
                <button type="submit" class="btn btn-danger"><i data-feather="trash"></i></button>
              </form>
            </td>
          </tr>
          @endforeach
          <tr>
            <th scope="row">Suma</th>
            <td></td>
            <td></td>
            <td>{{ $price }}</td>
            <td></td>
          </tr>
        </tbody>
      </table>

      <hr class="mb-4">
      <a role="button" href="{{ route('products.index') }}" class="btn btn-link btn-lg btn-block">Pridėti daugiau
        paslaugų</a>
    </div>
    <div class="col">
      @if ($price > 0)
      <form action="{{ route('cart.checkout') }}" method="POST">
        @csrf
        @component('components.admin.form-group', ['name' => 'customer_name'])
        @slot('title') Vardas @endslot
        <input id="customer_name" name="customer_name" value="{{ old('customer_name') }}" type="text"
          class="form-control @error('customer_name') is-invalid @enderror" placeholder="Vardenis Pavardenis" required>
        @error('customer_name')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
        @enderror
        @endcomponent

        @component('components.admin.form-group', ['name' => 'customer_phone'])
        @slot('title') Telefono numeris @endslot
        <input id="customer_phone" name="customer_phone" value="{{ old('customer_phone') }}" type="text"
          class="form-control @error('customer_phone') is-invalid @enderror" placeholder="+370..." required>
        @error('customer_phone')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
        @enderror
        @endcomponent

        @component('components.admin.form-group', ['name' => 'customer_email'])
        @slot('title') El. pašto adresas @endslot
        <input id="customer_email" name="customer_email" value="{{ old('customer_email') }}" type="email"
          class="form-control @error('customer_email') is-invalid @enderror" placeholder="@" required>
        @error('customer_email')
        <div class="invalid-feedback">
          {{ $message }}
        </div>
        @enderror
        @endcomponent

        <hr class="mb-4">
        <button type="submit" class="btn btn-primary btn-lg btn-block">Užsakyti</button>
      </form>
      @endif
    </div>
  </div>
</div>
@endsection