musu_webukas/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index']);
Route::resource('categories', 'CategoryController')->only(['show']);
Route::resource('cart', 'CartController')->only(['index', 'store', 'destroy']);
Route::post('/checkout', 'CartController@checkout')->name('cart.checkout');
Route::resource('contacts', 'ContactController')->only(['index', 'store']);

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('orders', 'OrderController')->only(['index', 'show', 'destroy']);
    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoryController');
    Route::resource('contacts', 'ContactController')->only(['index', 'destroy']);
});

musu_webukas/app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'phone', 'email', 'text'];
}

musu_webukas/app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contact;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contacts = Contact::all();
        return view('admin.contacts.index', ['contacts' => $contacts]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Contact  $contact
     * @return \Illuminate\Http\Response
     */
    public function destroy(Contact $contact)
    {
        $contact->delete();
        return redirect()->route('admin.contacts.index');
    }
}

musu_webukas/app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use App\Http\Requests\StoreContact;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('contacts.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreContact  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreContact $request)
    {
        Contact::create($request->validated());
        return view('contacts.success');
    }
}

musu_webukas/resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('title', 'Susisiekite su mumis')

@section('content')
@if ($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<div class="container">
  <form action="{{ route('contacts.store') }}" method="POST">
    @csrf

    @component('components.admin.form-group', ['name' => 'name'])
    @slot('title') Vardas @endslot
    <input id="name" name="name" value="{{ old('name') }}" type="text"
      class="form-control @error('name') is-invalid @enderror" placeholder="Vardenis Pavardenis" required>
    @error('name')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
    @endcomponent

    @component('components.admin.form-group', ['name' => 'phone'])
    @slot('title') Telefono numeris @endslot
    <input id="phone" name="phone" value="{{ old('phone') }}" type="text"
      class="form-control @error('phone') is-invalid @enderror" placeholder="+370..." required>
    @error('phone')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
    @endcomponent

    @component('components.admin.form-group', ['name' => 'email'])
    @slot('title') El. pašto adresas @endslot
    <input id="email" name="email" value="{{ old('email') }}" type="email"
      class="form-control @error('email') is-invalid @enderror" placeholder="@" required>
    @error('email')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
    @endcomponent

    @component('components.admin.form-group', ['name' => 'text'])
    @slot('title') Užklausa @endslot
    <textarea name="text" id="text" cols="30" rows="10" class="form-control @error('text') is-invalid @enderror"
      placeholder="Užklausa" required>{{ old('text') }}</textarea>
    @error('text')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
    @endcomponent

    <hr class="mb-4">
    <button type="submit" class="btn btn-primary btn-lg btn-block">Klausti</button>
  </form>
</div>
@endsection

musu_webukas/resources/views/contacts/success.blade.php
@extends('layouts.app')

@section('title', "Jūsų užklausa sėkmingai priimta")

@section('content')
<div class="container">
  <a role="button" class="btn btn-primary btn-lg btn-block" href="{{ route('products.index') }}">Grįžti į paslaugų
    sąrašą</a>
</div>
@endsection