musu_webukas/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index']);
Route::resource('categories', 'CategoryController')->only(['show']);
Route::resource('cart', 'CartController')->only(['index', 'store', 'destroy']);
Route::post('/checkout', 'CartController@checkout')->name('cart.checkout');
Route::resource('contacts', 'ContactController')->only(['index', 'store']);

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('orders', 'OrderController')->only(['index', 'show', 'destroy']);
    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoryController');
    Route::resource('contacts', 'ContactController')->only(['index', 'destroy']);
});

musu_webukas/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title'];

    /**
     * Get the products belonging to this category.
     */
    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

musu_webukas/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCategory;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categories.index', ['categories' => Category::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreCategory  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCategory $request)
    {
        $category = Category::create($request->validated());
        return redirect()->route('admin.categories.show', ['id' => $category->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', ['category' => $category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreCategory  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCategory $request, Category $category)
    {
        $category->update($request->validated());
        return redirect()->route('admin.categories.show', ['id' => $category->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('admin.categories.index');
    }
}

musu_webukas/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('categories.show', ['category' => $category, 'categories' => Category::all()]);
    }
}

musu_webukas/resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('title', 'Nauja kategorija')

@section('content')
<form action="{{ route('admin.categories.store') }}" method="POST">
  @csrf
  @component('components.admin.form-group', ['name' => 'title'])
  @slot('title') Pavadinimas @endslot
  <input id="title" name="title" value="{{ old('title') }}" type="text"
    class="form-control @error('title') is-invalid @enderror" placeholder="Kategorijos pavadinimas" required>
  @error('title')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent
  <hr class="mb-4">
  <button type="submit" class="btn btn-primary btn-lg btn-block">Sukurti</button>
</form>
@endsection

musu_webukas/resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('title', 'Keisti kategoriją')

@section('content')
<form action="{{ route('admin.categories.update', ['category' => $category]) }}" method="POST">
  @method('PUT')
  @csrf
  @component('components.admin.form-group', ['name' => 'title'])
  @slot('title') Pavadinimas @endslot
  <input id="title" name="title" value="{{ old('title', $category->title) }}" type="text"
    class="form-control @error('title') is-invalid @enderror" placeholder="Kategorijos pavadinimas" required>
  @error('title')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent
  <hr class="mb-4">
  <button type="submit" class="btn btn-primary btn-lg btn-block">Išsaugoti</button>
</form>
@endsection

musu_webukas/resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('title', 'Kategorijos')

@section('buttons')
<div class="btn-group mr-2">
  <a role="button" class="btn btn-sm btn-primary" href={{ route('admin.categories.create') }}>
    <i data-feather="plus-circle"></i>
    Nauja kategorija
  </a>
</div>
@endsection

@section('content')
@component('components.admin.data-table')
@slot('headings')
<th scope="col">#</th>
<th scope="col">Pavadinimas</th>
@endslot
@foreach ($categories as $category)
<tr>
  <th scope="row">{{ $category->id }}</th>
  <td>
    <a href={{ route('admin.categories.show', ['id' => $category->id]) }}>
      {{ $category->title }}
    </a>
  </td>
</tr>
@endforeach
@endcomponent
@endsection

musu_webukas/resources/views/admin/categories/show.blade.php
@extends('layouts.admin')

@section('title', $category->title)

@section('buttons')
<div class="btn-group mr-2">
  <a role="button" class="btn btn-sm btn-primary" href={{ route('admin.categories.edit', ['id' => $category->id]) }}>
    <i data-feather="edit"></i>
    Keisti
  </a>
  <button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
    data-target="#delete-category-{{ $category->id }}">
    <i data-feather="trash"></i>
    Ištrinti
  </button>
</div>

@component('components.admin.modal', ['id' => "delete-category-$category->id"])
@slot('title') Ištrinti {{ $category->title }} @endslot
Ar tikrai norite ištrinti <code>{{ $category->title }}</code>?
@slot('buttons')
<button type="button" class="btn btn-primary" data-dismiss="modal">Atšaukti</button>
<button type="button" class="btn btn-danger"
  onclick="document.getElementById('delete-category-{{ $category->id }}-form').submit();">Ištrinti</button>
@endslot
@endcomponent
<form id="delete-category-{{ $category->id }}-form"
  action="{{ route('admin.categories.destroy', ['id' => $category->id]) }}" method="POST" style="display: none;">
  @csrf
  @method('DELETE')
</form>
@endsection

@section('content')
<h3>Paslaugos</h3>
@component('components.admin.products.table', ['products' => $category->products]) @endcomponent
@endsection