musu_webukas/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::resource('products', 'ProductController')->only(['index']);
Route::resource('categories', 'CategoryController')->only(['show']);
Route::resource('cart', 'CartController')->only(['index', 'store', 'destroy']);
Route::post('/checkout', 'CartController@checkout')->name('cart.checkout');
Route::resource('contacts', 'ContactController')->only(['index', 'store']);

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('auth')->group(function () {
    Route::get('/', 'DashboardController')->name('dashboard');
    Route::resource('orders', 'OrderController')->only(['index', 'show', 'destroy']);
    Route::resource('products', 'ProductController');
    Route::resource('categories', 'CategoryController');
    Route::resource('contacts', 'ContactController')->only(['index', 'destroy']);
});

musu_webukas/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'price', 'quantifiable', 'category_id'];

    /**
     * Get the category of this product.
     */
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    /**
     * The orders that have this product.
     */
    public function orders()
    {
        return $this->belongsToMany('App\Order')->using('App\OrderProduct')->withPivot('quantity');
    }
}

musu_webukas/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Product;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreProduct;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.products.index', ['products' => Product::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create', ['categories' => Category::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProduct  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProduct $request)
    {
        $product = new Product;
        $product->fill($request->validated());
        $product->quantifiable = $request->has('quantifiable');
        $product->photoPath = $request->file('photo')->store('public');
        $product->save();
        return redirect()->route('admin.products.show', ['id' => $product->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('admin.products.show', ['product' => $product]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.products.edit', ['product' => $product, 'categories' => Category::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\StoreProduct  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(StoreProduct $request, Product $product)
    {
        $product->fill($request->validated());
        $product->quantifiable = $request->has('quantifiable');
        if ($request->has('photo')) {
            Storage::delete($product->photoPath);
            $product->photoPath = $request->file('photo')->store('public');
        }
        $product->save();
        return redirect()->route('admin.products.show', ['id' => $product->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        Storage::delete($product->photoPath);
        $product->delete();
        return redirect()->route('admin.products.index');
    }
}

musu_webukas/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index', ['products' => Product::all(), 'categories' => Category::all()]);
    }
}

musu_webukas/resources/views/admin/products/create.blade.php
@extends('layouts.admin')

@section('title', 'Nauja paslauga')

@section('content')
<form action="{{ route('admin.products.store') }}" method="POST" enctype="multipart/form-data">
  @csrf

  @component('components.admin.form-group', ['name' => 'category_id'])
  @slot('title') Kategorija @endslot
  <div class="input-group">
    <select class="custom-select @error('category') is-invalid @enderror" id="category_id" name="category_id" required>
      @foreach ($categories as $category)
      <option @if (old('category_id')==$category->id) selected @endif value="{{ $category->id }}">
        {{ $category->title }}
      </option>
      @endforeach
    </select>
    <div class="input-group-append">
      <a role="button" class="btn btn-primary" href="{{ route('admin.categories.create') }}">Nauja kategorija</a>
    </div>
  </div>
  @error('category_id')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  @component('components.admin.form-group', ['name' => 'title'])
  @slot('title') Pavadinimas @endslot
  <input id="title" name="title" value="{{ old('title') }}" type="text"
    class="form-control @error('title') is-invalid @enderror" placeholder="Paslaugos pavadinimas" required>
  @error('title')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  @component('components.admin.form-group', ['name' => 'description'])
  @slot('title') Aprašymas @endslot
  <textarea name="description" id="description" cols="30" rows="10"
    class="form-control @error('description') is-invalid @enderror" placeholder="Paslaugos aprašymas"
    required>{{ old('description') }}</textarea>
  @error('description')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  <div class="form-row">
    <div class="col">
      <label for="price">Kaina</label>
      <div class="input-group">
        <input id="price" name="price" value="{{ old('price') }}" type="number" step="0.01"
          class="form-control @error('price') is-invalid @enderror" placeholder="0.00" required>
        <div class="input-group-append">
          <span class="input-group-text">&euro;</span>
        </div>
      </div>
      @error('price')
      <div class="invalid-feedback">
        {{ $message }}
      </div>
      @enderror
    </div>
    <div class="col">
      <label for="photo">Nuotrauka</label>
      <input type="file" name="photo" class="form-control-file @error('price') is-invalid @enderror" id="photo"
        required>
      @error('photo')
      <div class="invalid-feedback">
        {{ $message }}
      </div>
      @enderror
    </div>
  </div>
  <div class="form-group form-check">
    <input name="quantifiable" type="checkbox" @if (old('quantifiable')) checked @endif id="quantifiable"
      class="form-check-input @error('price') is-invalid @enderror">
    <label class="form-check-label" for="quantifiable">
      Paslaugą galima užsisakyti su kiekiu
    </label>
    @error('quantifiable')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
  </div>
  <hr class="mb-4">
  <button type="submit" class="btn btn-primary btn-lg btn-block">Sukurti</button>
</form>
@endsection

musu_webukas/resources/views/admin/products/edit.blade.php
@extends('layouts.admin')

@section('title', 'Keisti paslaugą')

@section('content')
<form action="{{ route('admin.products.update', ['product' => $product]) }}" method="POST"
  enctype="multipart/form-data">
  @method('PUT')
  @csrf

  @component('components.admin.form-group', ['name' => 'category_id'])
  @slot('title') Kategorija @endslot
  <div class="input-group">
    <select class="custom-select @error('category') is-invalid @enderror" id="category_id" name="category_id" required>
      @foreach ($categories as $category)
      <option @if (old('category_id', $product->category_id)==$category->id) selected @endif
        value="{{ $category->id }}">
        {{ $category->title }}
      </option>
      @endforeach
    </select>
    <div class="input-group-append">
      <a role="button" class="btn btn-primary" href="{{ route('admin.categories.create') }}">Nauja kategorija</a>
    </div>
  </div>
  @error('category_id')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  @component('components.admin.form-group', ['name' => 'title'])
  @slot('title') Pavadinimas @endslot
  <input id="title" name="title" value="{{ old('title', $product->title) }}" type="text"
    class="form-control @error('title') is-invalid @enderror" placeholder="Paslaugos pavadinimas" required>
  @error('title')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  @component('components.admin.form-group', ['name' => 'description'])
  @slot('title') Aprašymas @endslot
  <textarea name="description" id="description" cols="30" rows="10"
    class="form-control @error('description') is-invalid @enderror" placeholder="Paslaugos aprašymas"
    required>{{ old('description', $product->description) }}</textarea>
  @error('description')
  <div class="invalid-feedback">
    {{ $message }}
  </div>
  @enderror
  @endcomponent

  <div class="form-row">
    <div class="col">
      <label for="price">Kaina</label>
      <div class="input-group">
        <input id="price" name="price" value="{{ old('price', $product->price) }}" type="number" step="0.01"
          class="form-control @error('price') is-invalid @enderror" placeholder="0.00" required>
        <div class="input-group-append">
          <span class="input-group-text">&euro;</span>
        </div>
      </div>
      @error('price')
      <div class="invalid-feedback">
        {{ $message }}
      </div>
      @enderror
    </div>
    <div class="col">
      <label for="photo">Nauja nuotrauka</label>
      <input type="file" name="photo" class="form-control-file @error('photo') is-invalid @enderror" id="photo">
      @error('photo')
      <div class="invalid-feedback">
        {{ $message }}
      </div>
      @enderror
    </div>
  </div>
  <div class="form-group form-check">
    <input name="quantifiable" type="checkbox" id="quantifiable"
      class="form-check-input @error('price') is-invalid @enderror" @if (old('quantifiable', $product->quantifiable))
    checked @endif>
    <label class="form-check-label" for="quantifiable">
      Paslaugą galima užsisakyti su kiekiu
    </label>
    @error('quantifiable')
    <div class="invalid-feedback">
      {{ $message }}
    </div>
    @enderror
  </div>
  <hr class="mb-4">
  <button type="submit" class="btn btn-primary btn-lg btn-block">Išsaugoti</button>
</form>
@endsection

musu_webukas/resources/views/admin/products/index.blade.php
@extends('layouts.admin')

@section('title', 'Paslaugos')

@section('buttons')
<div class="btn-group mr-2">
  <a role="button" class="btn btn-sm btn-primary" href={{ route('admin.products.create') }}>
    <i data-feather="plus-circle"></i>
    Nauja paslauga
  </a>
</div>
@endsection

@section('content')
@component('components.admin.products.table', ['products' => $products]) @endcomponent
@endsection

musu_webukas/resources/views/admin/products/show.blade.php
@extends('layouts.admin')

@section('title', $product->title)

@section('buttons')
<div class="btn-group mr-2">
  <a role="button" class="btn btn-sm btn-primary" href={{ route('admin.products.edit', ['product' => $product]) }}>
    <i data-feather="edit"></i>
    Keisti
  </a>
  <button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
    data-target="#delete-product-{{ $product->id }}">
    <i data-feather="trash"></i>
    Ištrinti
  </button>
</div>
@component('components.admin.modal', ['id' => "delete-product-$product->id", 'title' => "Ištrinti $product->title"])
@slot('title') Ištrinti {{ $product->title }} @endslot
Ar tikrai norite ištrinti <code>{{ $product->title }}</code>?
@slot('buttons')
<button type="button" class="btn btn-primary" data-dismiss="modal">Atšaukti</button>
<button type="button" class="btn btn-danger"
  onclick="document.getElementById('delete-product-{{ $product->id }}-form').submit();">Ištrinti</button>
@endslot
@endcomponent
<form id="delete-product-{{ $product->id }}-form"
  action="{{ route('admin.products.destroy', ['product' => $product]) }}" method="POST" style="display: none;">
  @csrf
  @method('DELETE')
</form>
@endsection

@section('content')
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a
        href="{{ route('admin.categories.show', ['category' => $product->category]) }}">{{ $product->category->title }}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">{{ $product->title }}</li>
  </ol>
</nav>
<img src="{{ Storage::url($product->photoPath) }}" alt="{{ $product->title }}" class="img-thumbnail"
  style="max-width: 512px">
<p>{{ $product->description }}</p>
<p>@if ($product->quantifiable) Šią paslaugą galima užsisakyti su kiekiu @else Galima užsisakyti tik vieną paslaugą
  @endif</p>
<p>Kaina {{ $product->price }} &euro;</p>
@endsection